feat(Web, Home): API Integration
evilfactorylabs/gow pull request #8
Opened 2020-02-26 21:29 UTC by ri7nz

2020-02-27 09:04 UTC, faultable commented
The logs is [here](https://privatebin.net/?8f264a4c57f69105#AHS9r1AsLS6nLFrSjeL8XYYG3NDbKKQnnGTH4XMzmfJN) in case you can't access it

2020-03-29 05:31 UTC, faultables requested changes
![Screen Shot 2020-03-29 at 12 31 08 PM](https://user-images.githubusercontent.com/6561394/77841123-2f058200-71b9-11ea-90a0-00db89f31263.png)

2020-03-29 05:31 UTC, faultable commented on web/package.json
> +    "bs-platform": "^6.2.1",
ada apa di downgrade?

2020-03-29 05:31 UTC, faultables approved these changes

2020-03-29 05:32 UTC, faultable commented
salah pencet tadi hampura

2020-03-29 05:34 UTC, ri7nz commented on web/package.json
> +    "bs-platform": "^6.2.1",
waktu ngetrace gan kenapa gak work di alpine.

2020-03-29 05:37 UTC, faultable commented on web/package.json
> +    "bs-platform": "^6.2.1",
bebas gan

2020-03-29 06:26 UTC, merged